/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.modul01;

/**
 *
 * @author qeysa
 */
public class modul4 extends javax.swing.JFrame {

    /**
     * Creates new form modul4
     */
    public modul4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MAKANAN = new javax.swing.JComboBox<>();
        MINUMAN = new javax.swing.JComboBox<>();
        SAYURAN = new javax.swing.JComboBox<>();
        PESAN = new javax.swing.JButton();
        HASIL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MAKANAN");

        jLabel2.setText("MINUMAN");

        jLabel3.setText("SAYURAN");

        MAKANAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AYAM", "BAKSO", "IKAN", "TAHU" }));
        MAKANAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAKANANActionPerformed(evt);
            }
        });

        MINUMAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COCA COLA", "SPRITE'", "TEH GELAS", "AQUA", " " }));
        MINUMAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINUMANActionPerformed(evt);
            }
        });

        SAYURAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WORTEL", "KANGKUNG", "TOMAT", "TIMUN", " " }));
        SAYURAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAYURANActionPerformed(evt);
            }
        });

        PESAN.setText("PESAN");
        PESAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MAKANAN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(SAYURAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MINUMAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PESAN)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAKANAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MINUMAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAYURAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PESAN)
                    .addComponent(HASIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PESANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESANActionPerformed
 String Makanan = (String) MAKANAN.getSelectedItem();
        String Minuman = (String) MINUMAN.getSelectedItem();
        String Sayuran = (String) SAYURAN.getSelectedItem();
        
        String hasil = "  Food: " + Makanan + "   Drinks: " + Minuman + "   Vegetable: " + Sayuran;
        HASIL.setText(hasil);      // TODO add your handling code here:
    }//GEN-LAST:event_PESANActionPerformed

    private void MAKANANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAKANANActionPerformed
        // TODO add your handling code here:
    int IndexCombo;
        String Pilihan;
        
        //untuk mengetahui index atau urutan keberapa dari daftar combo
        IndexCombo = MAKANAN.getSelectedIndex();
                 
        //untuk mengetahui string atau text dari combo yang dipilih
        Pilihan = (String)MAKANAN.getSelectedItem();
        HASIL.setText(Pilihan);      
    }//GEN-LAST:event_MAKANANActionPerformed

    private void MINUMANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINUMANActionPerformed
        // TODO add your handling code here: 
        int IndexCombo;
        String Pilihan;
        
        //untuk mengetahui index atau urutan keberapa dari daftar combo
        IndexCombo = MINUMAN.getSelectedIndex();
                 
        //untuk mengetahui string atau text dari combo yang dipilih
        Pilihan = (String)MINUMAN.getSelectedItem();
        HASIL.setText(Pilihan);  
    }//GEN-LAST:event_MINUMANActionPerformed

    private void SAYURANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAYURANActionPerformed
        // TODO add your handling code here:
        int IndexCombo;
        String Pilihan;
        
        //untuk mengetahui index atau urutan keberapa dari daftar combo
        IndexCombo = SAYURAN.getSelectedIndex();
                 
        //untuk mengetahui string atau text dari combo yang dipilih
        Pilihan = (String)SAYURAN.getSelectedItem();
        HASIL.setText(Pilihan);  
    }//GEN-LAST:event_SAYURANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HASIL;
    private javax.swing.JComboBox<String> MAKANAN;
    private javax.swing.JComboBox<String> MINUMAN;
    private javax.swing.JButton PESAN;
    private javax.swing.JComboBox<String> SAYURAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
